# Generated by Django 5.2.3 on 2025-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_branch_alter_user_role_alter_user_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
