# Generated by Django 5.2.3 on 2025-06-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification_alter_user_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wp_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
