# Generated by Django 5.2.3 on 2025-06-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_wp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wp_number',
            field=models.CharField(default=8862887291, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
