# Generated by Django 5.2.3 on 2025-06-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('negotiable', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Books & Study Materials', 'Books & Study Materials'), ('Hostel Essentials', 'Hostel Essentials'), ('Furniture', 'Furniture'), ('Sports & Fitness', 'Sports & Fitness'), ('Cycle & Transport', 'Cycle & Transport'), ('Room Decor', 'Room Decor'), ('Lab Equipment', 'Lab Equipment'), ('Others', 'Others')], default='Others', max_length=50)),
                ('is_sold', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
